using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TinyResult;

namespace TodoListApp.Api.Controllers;

/// <summary>
/// Base controller that provides common properties and methods
/// for API controllers, such as retrieving the current user's ID.
/// </summary>
public abstract class BaseController : ControllerBase
{
    /// <summary>
    /// Gets the current user's ID.
    /// </summary>
    /// <remarks>
    /// In this example, a fixed GUID is returned as a placeholder.
    /// In a real application, this value should be retrieved
    /// from the authentication context or JWT token.
    /// </remarks>
    protected static Guid CurrentUserId => Guid.Parse("b3d5f0a1-6c3b-4a2e-9f1c-123456789abc");

    /// <summary>
    /// Converts an application <see cref="Result{T}"/> into a corresponding HTTP response.
    /// </summary>
    /// <typeparam name="T">The type of the result value.</typeparam>
    /// <param name="result">The application result to handle.</param>
    /// <returns>
    /// An <see cref="OkObjectResult"/> if the result is successful;
    /// otherwise, a corresponding error response based on the error code.
    /// </returns>
    protected IActionResult HandleResult<T>(Result<T> result)
    {
        if (result.IsSuccess)
        {
            return this.Ok(result.Value);
        }

        return result.Error!.Code switch
        {
            TinyResult.Enums.ErrorCode.ValidationError => this.BadRequest(result.Error),
            TinyResult.Enums.ErrorCode.NotFound => this.NotFound(result.Error),
            _ => this.StatusCode(StatusCodes.Status500InternalServerError, result.Error)
        };
    }

    /// <summary>
    /// Handles a command result that does not return a value.
    /// </summary>
    /// <param name="result">The application result to handle.</param>
    /// <returns>
    /// A <see cref="NoContentResult"/> if the operation succeeds;
    /// otherwise, an error response generated by <see cref="HandleResult{T}"/>.
    /// </returns>
    protected IActionResult HandleNoContent(Result<bool> result)
    {
        if (result.IsSuccess)
        {
            return this.NoContent();
        }

        return this.HandleResult(result);
    }
}
